---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://web.example.com
        delay: 20

  rules:
    - name: Web site is up
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: Status
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: Fix
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
...
